"use client";
import { useEffect, useState } from "react";
import { Building2, CreditCard, Save } from "lucide-react";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/page-header";

const empty={businessName:"",phone:"",address:"",upiId:"",accountHolderName:"",bankAccountNumber:"",ifsc:""};
export default function SettingsPage(){
 const [form,setForm]=useState(empty); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 useEffect(()=>{api.settings.get().then(v=>setForm({...empty,...v})).catch(e=>setError(e instanceof Error?e.message:"Could not load settings")).finally(()=>setLoading(false))},[]);
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("");setError("");try{await api.settings.update(form);setMessage("Settings saved successfully.")}catch(e){setError(e instanceof Error?e.message:"Could not save settings")}finally{setSaving(false)}}
 if(loading)return <div className="card p-8 text-sm text-slate-500">Loading settings…</div>;
 return <div className="fade-in"><PageHeader eyebrow="System" title="Business settings" description="Configure the business details and UPI account used on invoices and payment QR codes."/>{message&&<div className="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div>}{error&&<div className="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}
 <form onSubmit={save} className="grid gap-5 xl:grid-cols-2"><section className="card p-5"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><Building2 size={19}/></div><div><h2 className="font-black">Business details</h2><p className="text-xs text-slate-500">Printed and displayed on billing screens.</p></div></div><div className="mt-5 space-y-4"><label className="block text-sm font-bold">Business name<input className="input mt-1.5" required value={form.businessName} onChange={e=>setForm({...form,businessName:e.target.value})}/></label><label className="block text-sm font-bold">Phone<input className="input mt-1.5" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="block text-sm font-bold">Address<textarea className="input mt-1.5 min-h-28" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label></div></section>
 <section className="card p-5"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><CreditCard size={19}/></div><div><h2 className="font-black">UPI & bank details</h2><p className="text-xs text-slate-500">The VPA powers the dynamic bill QR.</p></div></div><div className="mt-5 space-y-4"><label className="block text-sm font-bold">UPI ID / VPA<input className="input mt-1.5" placeholder="merchant@upi" value={form.upiId} onChange={e=>setForm({...form,upiId:e.target.value})}/></label><label className="block text-sm font-bold">Account holder name<input className="input mt-1.5" value={form.accountHolderName} onChange={e=>setForm({...form,accountHolderName:e.target.value})}/></label><label className="block text-sm font-bold">Bank account number<input className="input mt-1.5" value={form.bankAccountNumber} onChange={e=>setForm({...form,bankAccountNumber:e.target.value})}/></label><label className="block text-sm font-bold">IFSC<input className="input mt-1.5" value={form.ifsc} onChange={e=>setForm({...form,ifsc:e.target.value.toUpperCase()})}/></label><div className="rounded-xl bg-slate-50 p-3 text-xs text-slate-500">For a standard <code>upi://pay</code> QR, enter a UPI VPA. Bank account + IFSC are stored for bank details but are not themselves the UPI intent address.</div></div></section><div className="xl:col-span-2"><Button type="submit" disabled={saving}><Save size={16}/>{saving?"Saving…":"Save settings"}</Button></div></form></div>;
}
