"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Boxes, FilePlus2, IndianRupee, Users, AlertTriangle, ReceiptText } from "lucide-react";
import { api } from "@/lib/api";
import { formatCurrency, formatDate } from "@/lib/utils";
import type { Customer, Invoice, Product } from "@/types/billing";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/status-badge";
import { LoadingState } from "@/components/data-state";
import { PageHeader } from "@/components/page-header";
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip } from "recharts";

export default function Dashboard() {
  const [products, setProducts] = useState<Product[]>([]); const [customers, setCustomers] = useState<Customer[]>([]); const [invoices, setInvoices] = useState<Invoice[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { (async () => { try { const [p,c,i] = await Promise.all([api.products.list(), api.customers.list(), api.invoices.list()]); setProducts(p); setCustomers(c); setInvoices(i); } catch (e) { setError(e instanceof Error ? e.message : "Could not reach backend"); } finally { setLoading(false); } })(); }, []);
  const revenue = useMemo(() => invoices.reduce((sum, i) => sum + Number(i.total || 0), 0), [invoices]);
  const chartData = useMemo(() => [...invoices].reverse().map((i, idx) => ({ name: i.invoiceNumber.replace("INV-", "#"), value: Number(i.total || 0), idx })), [invoices]);
  const lowStock = products.filter(p => Number(p.stock) <= 5).slice(0, 5);
  if (loading) return <LoadingState label="Connecting to your billing backend…"/>;
  return <div className="fade-in"><PageHeader title="Dashboard" description="A clean command center for your day-to-day billing operations." actionHref="/invoices/new" actionLabel="Create invoice"/>{error && <div className="mb-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-800">{error}. Make sure Spring Boot is running on port 8000.</div>}
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      {[{label:"Total revenue",value:formatCurrency(revenue),icon:IndianRupee,sub:"From all bills"},{label:"Customers",value:customers.length,icon:Users,sub:"Live from backend"},{label:"Products",value:products.length,icon:Boxes,sub:`${lowStock.length} low-stock item${lowStock.length===1?"":"s"}`},{label:"Bills",value:invoices.length,icon:ReceiptText,sub:"Live from backend"}].map((s) => {const Icon=s.icon; return <div className="card p-5" key={s.label}><div className="flex items-start justify-between"><div className="grid size-11 place-items-center rounded-2xl bg-blue-50 text-blue-600"><Icon size={20}/></div><ArrowUpRight size={17} className="text-slate-300"/></div><div className="mt-5 text-2xl font-black tracking-tight">{s.value}</div><div className="mt-1 text-sm font-bold text-slate-700">{s.label}</div><div className="mt-1 text-xs text-slate-500">{s.sub}</div></div>})}
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.6fr_1fr]">
      <div className="card p-5"><div className="flex items-center justify-between"><div><h2 className="font-black">Revenue pulse</h2><p className="text-xs text-slate-500">Based on all bills in the backend</p></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-600">Live API data</span></div><div className="mt-5 h-72">{chartData.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize:11, fill:'#64748b'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:11, fill:'#64748b'}} tickFormatter={(v)=>`₹${Math.round(v/1000)}k`}/><Tooltip formatter={(v)=>formatCurrency(Number(v))}/><Area type="monotone" dataKey="value" stroke="#2563eb" fill="#dbeafe" strokeWidth={3}/></AreaChart></ResponsiveContainer> : <div className="grid h-full place-items-center text-center text-sm text-slate-400">Create your first invoice to populate revenue analytics.</div>}</div></div>
      <div className="card p-5"><div className="flex items-center justify-between"><div><h2 className="font-black">Inventory attention</h2><p className="text-xs text-slate-500">Items at or below 5 units</p></div><AlertTriangle size={18} className="text-amber-500"/></div><div className="mt-4 space-y-3">{lowStock.length ? lowStock.map(p => <div key={p.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><div className="min-w-0"><div className="truncate text-sm font-bold">{p.name}</div><div className="text-xs text-slate-500">{p.sku}</div></div><div className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-black text-amber-700">{p.stock} left</div></div>) : <div className="rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">Inventory looks healthy. No low-stock alerts.</div>}</div><Link href="/products" className="mt-4 inline-flex text-sm font-bold text-blue-600 hover:underline">Open products <ArrowUpRight size={15}/></Link></div>
    </div>
    <div className="mt-5 card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-black">Recent invoices</h2><p className="text-xs text-slate-500">Quick access to the latest bills from the backend.</p></div><Link href="/invoices" className="text-sm font-bold text-blue-600">View all</Link></div>{invoices.length ? <div className="divide-y divide-slate-100">{invoices.slice(0,5).map(i=><Link key={i.id} href={`/invoices/${i.id}`} className="flex items-center justify-between gap-4 p-4 transition hover:bg-slate-50"><div className="min-w-0"><div className="font-bold">{i.invoiceNumber}</div><div className="truncate text-xs text-slate-500">{i.customer?.name || "Walk-in customer"} · {formatDate(i.createdAt)}</div></div><div className="flex items-center gap-3"><StatusBadge status={i.status}/><div className="w-28 text-right font-black">{formatCurrency(i.total)}</div></div></Link>)}</div> : <div className="p-8 text-center text-sm text-slate-400">No bills yet. Create your first bill to populate this dashboard.</div>}</div>
    <div className="mt-5 grid gap-4 md:grid-cols-3"><Link href="/invoices/new" className="card group p-5 hover:border-blue-200"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><FilePlus2 size={19}/></div><div><div className="font-black">New invoice</div><div className="text-xs text-slate-500">Select products and customer</div></div><ArrowUpRight className="ml-auto text-slate-300 transition group-hover:text-blue-600" size={17}/></div></Link><Link href="/products" className="card group p-5 hover:border-blue-200"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-600"><Boxes size={19}/></div><div><div className="font-black">Manage catalogue</div><div className="text-xs text-slate-500">Create and retire products</div></div><ArrowUpRight className="ml-auto text-slate-300 transition group-hover:text-blue-600" size={17}/></div></Link><Link href="/customers" className="card group p-5 hover:border-blue-200"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><Users size={19}/></div><div><div className="font-black">Customer directory</div><div className="text-xs text-slate-500">Keep billing contacts fresh</div></div><ArrowUpRight className="ml-auto text-slate-300 transition group-hover:text-blue-600" size={17}/></div></Link></div>
  </div>
}
